// <auto-generated />
using System;
using DnDManager.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DnDManager.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260425164653_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DnDManager.Models.Campaign", b =>
                {
                    b.Property<int>("CampaignId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CampaignId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DmName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CampaignId");

                    b.ToTable("Campaigns");

                    b.HasData(
                        new
                        {
                            CampaignId = 1,
                            Description = "A classic starter campaign set in the Forgotten Realms.",
                            DmName = "Jared",
                            Name = "The Lost Mines of Phandelver"
                        });
                });

            modelBuilder.Entity("DnDManager.Models.Character", b =>
                {
                    b.Property<int>("CharacterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CharacterId"));

                    b.Property<int>("AC")
                        .HasColumnType("int");

                    b.Property<int>("CampaignId")
                        .HasColumnType("int");

                    b.Property<string>("Class")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CurrentHP")
                        .HasColumnType("int");

                    b.Property<int>("InitiativeBonus")
                        .HasColumnType("int");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<int>("MaxHP")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Race")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CharacterId");

                    b.HasIndex("CampaignId");

                    b.ToTable("Characters");

                    b.HasData(
                        new
                        {
                            CharacterId = 1,
                            AC = 18,
                            CampaignId = 1,
                            Class = "Fighter",
                            CurrentHP = 34,
                            InitiativeBonus = 2,
                            Level = 3,
                            MaxHP = 34,
                            Name = "Aldric Brightblade",
                            Race = "Human",
                            Status = "Active"
                        },
                        new
                        {
                            CharacterId = 2,
                            AC = 13,
                            CampaignId = 1,
                            Class = "Wizard",
                            CurrentHP = 20,
                            InitiativeBonus = 3,
                            Level = 3,
                            MaxHP = 20,
                            Name = "Sylvara Moonwhisper",
                            Race = "Elf",
                            Status = "Active"
                        },
                        new
                        {
                            CharacterId = 3,
                            AC = 14,
                            CampaignId = 1,
                            Class = "Rogue",
                            CurrentHP = 18,
                            InitiativeBonus = 4,
                            Level = 3,
                            MaxHP = 24,
                            Name = "Bram Thistlewick",
                            Race = "Halfling",
                            Status = "Active"
                        });
                });

            modelBuilder.Entity("DnDManager.Models.Combatant", b =>
                {
                    b.Property<int>("CombatantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CombatantId"));

                    b.Property<int>("ArmorClass")
                        .HasColumnType("int");

                    b.Property<int>("CampaignId")
                        .HasColumnType("int");

                    b.Property<int>("CurrentHP")
                        .HasColumnType("int");

                    b.Property<int>("Initiative")
                        .HasColumnType("int");

                    b.Property<bool>("IsDefeated")
                        .HasColumnType("bit");

                    b.Property<int>("MaxHP")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CombatantId");

                    b.HasIndex("CampaignId");

                    b.ToTable("Combatants");

                    b.HasData(
                        new
                        {
                            CombatantId = 1,
                            ArmorClass = 13,
                            CampaignId = 1,
                            CurrentHP = 0,
                            Initiative = 14,
                            IsDefeated = true,
                            MaxHP = 7,
                            Name = "Goblin Scout",
                            Type = "Enemy"
                        },
                        new
                        {
                            CombatantId = 2,
                            ArmorClass = 13,
                            CampaignId = 1,
                            CurrentHP = 7,
                            Initiative = 11,
                            IsDefeated = false,
                            MaxHP = 7,
                            Name = "Goblin Archer",
                            Type = "Enemy"
                        });
                });

            modelBuilder.Entity("DnDManager.Models.Encounter", b =>
                {
                    b.Property<int>("EncounterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EncounterId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Outcome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SessionLogId")
                        .HasColumnType("int");

                    b.HasKey("EncounterId");

                    b.HasIndex("SessionLogId");

                    b.ToTable("Encounters");

                    b.HasData(
                        new
                        {
                            EncounterId = 1,
                            Description = "Two goblins leap from the bushes along the trail.",
                            Name = "Goblin Ambush",
                            Outcome = "One goblin slain, one fled. Party took minor damage.",
                            SessionLogId = 1
                        });
                });

            modelBuilder.Entity("DnDManager.Models.LogEntry", b =>
                {
                    b.Property<int>("LogEntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogEntryId"));

                    b.Property<string>("ActionDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ActorName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("AttackRoll")
                        .HasColumnType("int");

                    b.Property<string>("ConditionApplied")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("DamageDealt")
                        .HasColumnType("int");

                    b.Property<int>("EncounterId")
                        .HasColumnType("int");

                    b.Property<int?>("HealingDone")
                        .HasColumnType("int");

                    b.Property<int?>("HpAfterAction")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoundNumber")
                        .HasColumnType("int");

                    b.Property<string>("TargetName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TurnOrder")
                        .HasColumnType("int");

                    b.HasKey("LogEntryId");

                    b.HasIndex("EncounterId");

                    b.ToTable("LogEntries");

                    b.HasData(
                        new
                        {
                            LogEntryId = 1,
                            ActionDescription = "Goblin Scout fires a shortbow at Bram.",
                            ActionType = "Attack",
                            ActorName = "Goblin Scout",
                            AttackRoll = 14,
                            DamageDealt = 6,
                            EncounterId = 1,
                            HpAfterAction = 18,
                            Notes = "Hit! Bram drops to 18 HP.",
                            RoundNumber = 1,
                            TargetName = "Bram Thistlewick",
                            TurnOrder = 1
                        },
                        new
                        {
                            LogEntryId = 2,
                            ActionDescription = "Bram retaliates with a sneak attack using his shortsword.",
                            ActionType = "Attack",
                            ActorName = "Bram Thistlewick",
                            AttackRoll = 18,
                            DamageDealt = 9,
                            EncounterId = 1,
                            HpAfterAction = 0,
                            Notes = "Critical sneak attack! Goblin Scout is defeated.",
                            RoundNumber = 1,
                            TargetName = "Goblin Scout",
                            TurnOrder = 2
                        },
                        new
                        {
                            LogEntryId = 3,
                            ActionDescription = "Sylvara casts Fire Bolt at the Goblin Archer.",
                            ActionType = "Spell",
                            ActorName = "Sylvara Moonwhisper",
                            AttackRoll = 12,
                            DamageDealt = 5,
                            EncounterId = 1,
                            HpAfterAction = 2,
                            Notes = "Hit for 5 fire damage.",
                            RoundNumber = 1,
                            TargetName = "Goblin Archer",
                            TurnOrder = 3
                        },
                        new
                        {
                            LogEntryId = 4,
                            ActionDescription = "Aldric charges and swings his longsword.",
                            ActionType = "Attack",
                            ActorName = "Aldric Brightblade",
                            AttackRoll = 16,
                            DamageDealt = 8,
                            EncounterId = 1,
                            HpAfterAction = 0,
                            Notes = "Goblin Archer is slain.",
                            RoundNumber = 1,
                            TargetName = "Goblin Archer",
                            TurnOrder = 4
                        });
                });

            modelBuilder.Entity("DnDManager.Models.SessionLog", b =>
                {
                    b.Property<int>("SessionLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SessionLogId"));

                    b.Property<int>("CampaignId")
                        .HasColumnType("int");

                    b.Property<string>("MajorOutcome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SessionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("SessionNumber")
                        .HasColumnType("int");

                    b.Property<string>("Summary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("SessionLogId");

                    b.HasIndex("CampaignId");

                    b.ToTable("SessionLogs");

                    b.HasData(
                        new
                        {
                            SessionLogId = 1,
                            CampaignId = 1,
                            MajorOutcome = "One goblin defeated; one escaped into the woods.",
                            Notes = "Bram took 6 damage from a goblin arrow.",
                            SessionDate = new DateTime(2024, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SessionNumber = 1,
                            Summary = "The party was ambushed by goblins on the road to Phandalin.",
                            Title = "Ambush on the Triboar Trail"
                        });
                });

            modelBuilder.Entity("DnDManager.Models.Character", b =>
                {
                    b.HasOne("DnDManager.Models.Campaign", "Campaign")
                        .WithMany("Characters")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campaign");
                });

            modelBuilder.Entity("DnDManager.Models.Combatant", b =>
                {
                    b.HasOne("DnDManager.Models.Campaign", "Campaign")
                        .WithMany("Combatants")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campaign");
                });

            modelBuilder.Entity("DnDManager.Models.Encounter", b =>
                {
                    b.HasOne("DnDManager.Models.SessionLog", "SessionLog")
                        .WithMany("Encounters")
                        .HasForeignKey("SessionLogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SessionLog");
                });

            modelBuilder.Entity("DnDManager.Models.LogEntry", b =>
                {
                    b.HasOne("DnDManager.Models.Encounter", "Encounter")
                        .WithMany("LogEntries")
                        .HasForeignKey("EncounterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Encounter");
                });

            modelBuilder.Entity("DnDManager.Models.SessionLog", b =>
                {
                    b.HasOne("DnDManager.Models.Campaign", "Campaign")
                        .WithMany("SessionLogs")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campaign");
                });

            modelBuilder.Entity("DnDManager.Models.Campaign", b =>
                {
                    b.Navigation("Characters");

                    b.Navigation("Combatants");

                    b.Navigation("SessionLogs");
                });

            modelBuilder.Entity("DnDManager.Models.Encounter", b =>
                {
                    b.Navigation("LogEntries");
                });

            modelBuilder.Entity("DnDManager.Models.SessionLog", b =>
                {
                    b.Navigation("Encounters");
                });
#pragma warning restore 612, 618
        }
    }
}
